title: Trezp's Site
description: A personal portfolio powered by Minimal Mistakes
url: "https://trezp.github.io"
baseurl: ""

remote_theme: "mmistakes/minimal-mistakes@4.27.2"

plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache

author:
  name: Trezp
  avatar: "/assets/images/bio-photo.jpg"
  bio: "A thoughtful portfolio showcasing my instructional design and content work."
